//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualClipBoard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualClipBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error access to {0}.
        /// </summary>
        internal static string AutoloadRegistryAccess {
            get {
                return ResourceManager.GetString("AutoloadRegistryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to autoload. (Checked = true in settings).
        /// </summary>
        internal static string Config_AutoLoad {
            get {
                return ResourceManager.GetString("Config_AutoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History file: .
        /// </summary>
        internal static string Config_Files {
            get {
                return ResourceManager.GetString("Config_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History size loaded from settings: .
        /// </summary>
        internal static string Config_LoadedHistorySize {
            get {
                return ResourceManager.GetString("Config_LoadedHistorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray size loaded from settings: .
        /// </summary>
        internal static string Config_LoadedTrayElements {
            get {
                return ResourceManager.GetString("Config_LoadedTrayElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default).
        /// </summary>
        internal static string Culture_Invariant {
            get {
                return ResourceManager.GetString("Culture_Invariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string Culture_Russian {
            get {
                return ResourceManager.GetString("Culture_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed.
        /// </summary>
        internal static string CultureChanged_Caption {
            get {
                return ResourceManager.GetString("CultureChanged_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application.
        /// </summary>
        internal static string CultureChanged_Text {
            get {
                return ResourceManager.GetString("CultureChanged_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error remoing autoload for {0} from registry.
        /// </summary>
        internal static string Info_AutoloadCheckedError {
            get {
                return ResourceManager.GetString("Info_AutoloadCheckedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program {0} removed from autoload in registry.
        /// </summary>
        internal static string Info_AutoloadOff {
            get {
                return ResourceManager.GetString("Info_AutoloadOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added to autoload in registry.
        /// </summary>
        internal static string Info_AutoloadOn {
            get {
                return ResourceManager.GetString("Info_AutoloadOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to history: {0}.
        /// </summary>
        internal static string Info_HistoryAdded {
            get {
                return ResourceManager.GetString("Info_HistoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History size changed: {0}.
        /// </summary>
        internal static string Info_HistorySizeChanged {
            get {
                return ResourceManager.GetString("Info_HistorySizeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray size changed: {0}.
        /// </summary>
        internal static string Info_TraySizeChanged {
            get {
                return ResourceManager.GetString("Info_TraySizeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TrayMenu_Exit {
            get {
                return ResourceManager.GetString("TrayMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TrayMenu_Settings {
            get {
                return ResourceManager.GetString("TrayMenu_Settings", resourceCulture);
            }
        }
    }
}
